---
project:
  output-dir: docs
  
format: 
  html: default
  pdf:   
    header-includes:
        - \usepackage{float}
        - \floatplacement{table}{H}  
    fontsize: 11pt
    geometry: 
      - top=20mm
      - left=15mm
      - right=10mm
---

# Homework 2

Individual assignments due in Canvas on Tuesday, 22 September

Group collaborative key due on Tuesday, 29 September

1.  On Homework #1 you worked with the data in problem 15, regarding age (in months) of unassisted walking among a sample of 240 children. In that problem, you found the mean, SE, and a 95% confidence interval for average age of walking. In that problem, you were not told the size of the population and so did not account for the fpc. It turns out the data were collected from a pediatric outpatient clinic that serves 5850 children.

    a. Define/describe the following terms for this problem:
       i) Objective of the study
       ii) Target population
       iii) Observation unit
       iv) Population size
       v) Characteristic of interest
       vi) Sample unit
       vii) Sample size
       viii) Sample design
       ix) Number of possible samples for this design (it's okay to leave as a function of factorials)
       x) Inclusion probability
       xi) Sampling weight
       xii) fpc
    b. Use hand calculations to adjust the SE and 95% confidence intervals for the fpc.
    c. Use `svymean` in R to verify the values from (b).
    d. Do you think the fpc can be ignored for this problem? Explain your reasoning.
    e. Suppose the researchers want to conduct another study at the same clinic, and have enough funding to collect data on 500 children. The researchers want to calculate a 99% confidence interval for the mean age of walking. What will the margin of error be? Use the knowledge learned from the initial study, and do not ignore the fpc.
	  f. Suppose the researchers want to carry out a new study to estimate the proportion of children who begin walking before 11 months.  If we want a margin of error of 3.5% for a 95% confidence interval for the proportion, what sample size would we need to achieve this goal?  Do not use information from the study already conducted.  You may assume $N$ is large for this problem and the fpc can be ignored.
	  
2. Book problems from Chapter 2: #12 (Arizona cities; #35 in my online book), #13 (objects in bins; #36 in my online book; on part (a), use the seed=91811), #16(a) (Cullen (1994); #21 in my online book), #18 (SSC; #27 in my online book)

       

