# An Introduction to Probability Samples

Before we can jump into sampling designs, we need to establish a few basic concepts and notation. The sampling designs we're going to discuss are **probability samples**.

:::callout-tip
# Definition: Probability sample

A **probability sample**

\
\
\
\


:::

Throughout this semester we'll discuss three different ways to design a probability sample, as well as the properties of estimators arising from these designs. Probability samples allow us to avoid selection biases and help ensure the sample is representative of the population, as probability samples take selection choice away from the researcher, and put it in the hands of random selection. The three major designs we'll discuss are:

- Simple random sampling

\
\

- Stratified random sampling

\
\

- Cluster sampling

\
\

We'll also consider **systematic sampling**

\

\newpage

To simplify things, we'll make the following assumptions:

\
\
\
\
\
\
\
\
\
\

Depending on how far we get, we may revisit relaxing some of these assumptions at the end of the semester.

In all cases, our goal is to learn about some characteristic of the target population

\
\
\

and we'll use our sample data to estimate that characteristic. We'll also estimate standard errors, and use those to construct confidence intervals for the unknown population characteristic. We'll also discuss determining the necessary sample size.

## Probability Sampling Definitions and Notation

Throughout this semester, we'll assume a finite population, or **universe** of $N$ units:

\
\
\

Any sample we select from $\mathcal{U}$ will be a subset of $\mathcal{U}$, and we'll denote the specific sample chosen as $\mathcal{S}$. $\mathcal{S}$ contains $n$ elements from $\mathcal{U}$.

\
\
\
\

\newpage

**Example**: Suppose $\mathcal{U}=\{1,2,3,4,5\}$ and we consider samples of size $n=3$. There are 10 possible samples that could be selected:

\
\
\
\
\
\
\
\
\
\
\

Remember that in **probability sampling**

\
\
\
\
\

Because each possible sample $\mathcal{S}$ has a known probability of being selected, each unit in the universe $\mathcal{U}$ also has a known probability of being in the selected sample.

\
\
\
\
\
\

Let $y_i$ be

\

We consider $y_i$ to a be a *fixed quantity*.

\
\

\newpage

## Probability Samples: Inference Basics

We want to use the data from a sample to estimate some characteristic of the population. Common population characteristics of interest are

\
\
\
\
\
\
\
\
\
\
\
\
\

**Example**: Earlier we considered the universe $\mathcal{U}=\{1,2,3,4,5\}$. Suppose the values of $y_i$ are

| $i$   | 1   | 2   | 3   | 4   | 5   |
|-------|-----|-----|-----|-----|-----|
| $y_i$ | 2   | 4   | 4   | 6   | 6   |

\
\

We also considered taking samples of size $n=3$ from $\mathcal{U}$. There are 10 possible samples, and all are equally likely.

\
\
\
\
\
\
\
\

\newpage

Just like in other classes like STAT 102, 380, 212 our inference methods are going to rely on the **sampling distribution** of a statistic.

:::callout-tip
# Definition: Sampling Distribution
The **sampling distribution**

\
\
\

:::

**Example, cont.**:

\
\
\
\
\
\
\
\
\

From the sampling distribution, we can find properties of the estimator we're using.

\

- **Expected value**:
    
\
\
\
\
\
\
\

\newpage

- **Estimation bias**:
    
\
\
\
\
\
\
\
\



- **Variance**:
    
\
\
\
\
\
\
\
\
\
\
\
\
\
\
    
- **Mean squared error**:

\
\
\
\
\
\
\
\
