---
project:
  output-dir: docs
  
format: 
  html: default
  pdf:   
    header-includes:
        - \usepackage{float}
        - \floatplacement{table}{H}  
    fontsize: 11pt
    geometry: 
      - top=20mm
      - left=15mm
      - right=10mm
---

# **STAT 414: Introduction to Survey Sampling**

**Instructor:** Dr. Erin Blankenship (she/her)

**email:** `erin.blankenship@unl.edu`

**Lecture:** 2:00-3:15 Tuesday/Thursday, A130 Animal Science

**Office Hours:** 9:00-10:00 Tuesday/Thursday or by appointment; 343B Hardin Hall, North Wing

**Required Materials:**

- Lohr, S. (2022) Sampling Design and Analysis, 3$^{rd}$ edition. A digital version of the textbook will be linked through Canvas as part of a UNL textbook project, and the cost of the book will added to your student account.
- Supplementary (free downloadable) books on using R and SAS software may be found at [Dr. Lohr's website.](https://www.sharonlohr.com/sampling-design-and-analysis-3e)

**Prerequisites:** STAT 262, STAT 380, or STAT 318

**Course Description:** Sampling frames, methodology, questionnaire design.  Basics of
standard sampling plans including simple random sampling, ratio estimators,
stratified sampling, and cluster sampling.   More advanced topics may include
complex surveys, nonresponse, confidentiality problems, and adaptive methods.

**Course Goals:**

- Learn the basic methodology of how classical survey samples are conducted based
on simple random sampling.

- Recognize sampling and non-sampling errors.

- Be able to use extra information in sampling via ratio estimators and regression estimators.

- Be able to define and use stratified samples and know why they are often better than SRS.

- Be able to design one and two stage cluster samples and know their key properties.

- Recognize strengths and weaknesses of different sampling approaches.

- Use standard R packages to analyze survey data and estimate population means, proportions, totals, and more.

\
\

**Grading:**

| Assignment(s)      | Contribution to Final Grade |
|--------------------|-----------------------------|
| Homework/Participation             | 30%                         |
| Exam 1             | 20%                         |
| Exam 2           | 20%                         |
| Final Project      | 30%                         |

\

\newpage

**Grading Scale:**

| Grade | Final Percentage Range |
|-------|------------------------|
| A     | 94.0-100               |
| A-    | 90.0-93.99             |
| B+    | 88.0-89.99             |
| B     | 84.0-87.99             |
| B-    | 80.0-83.99             |
| C+    | 78.0-79.99             |
| C     | 74.0-77.99             |
| C-    | 70.0-73.99             |
| D+    | 68.0-69.99             |
| D     | 64.0-67.99             |
| D-    | 60.0-63.99             |
| F     | \<60.0                 |

\
**Course Expectations:** In this course, you are expected to have professional behavior. You are expected to attend all class meetings, be curious, ask questions, seek opportunities to learn, and be open and responsive to constructive feedback. In addition:

- Be an active participant--statistics is not a spectator sport!

- Be committed, take your work seriously

- Engage with the in-class activities and labs

- Help others--if you understand the material being discussed, practice your mentoring skills. This does not means sharing answers, but instead helping others understand the concepts.

- Complete any assigned readings.

You are also expected to exhibit a professional demeanor (language, attitude) toward others. Disagreement during discussions is welcome and often productive in developing a deeper understanding of the concepts being discussed. However, disagreement does not warrant yelling or disrespectful language or behavior. Unprofessional behavior will not be tolerated, and appropriate actions will be taken to prevent future occurrences.

**Recording of class-related activity:** I invite all of you to join me in actively creating and contributing to a positive, productive, and respectful classroom culture. Each student contributes to an environment that shapes the learning process. Any work and/or communication that you are privy to as a member of this course should be treated as the intellectual property of the speaker/creator, and is not to be shared outside the context of this course.

Students may not make or distribute screen captures, audio/video recordings of, or livestream, any class-related activity, including lectures and presentations, without express prior written consent from me or an approved accommodation from Services for Students with Disabilities. If you have (or think you may have) a disability such that you need to record or tape class-related activities, you should contact Services for Students with Disabilities. If you have an accommodation to record class-related activities, those recordings may not be shared with any other student, whether in this course or not, or with any other person or on any other platform.

**Homework:**  Approximately 6-8 homework assignments will be made over the course of the semester, and you will have one week to work on it. Homework will be turned in individually, and graded for completion. Over the following week, you will work collaboratively in a group to create a key for the homework. As a group, you will generate and refine answers to the homework questions, using your original submissions as a starting point. The end product will be a single, complete set of solutions with explanation for each homework problem. To earn participation credit, you must fully engage in the group solution (i.e., adding a comment like "This looks good" is not meaningful engagement) by making at least 3 contributions to each answer key. Contributions do not need to be answers! They can be clarifications, explanations, corrections, etc. More details on collaborative keys logistics will be provided with the first assignment. Other participation activities may be utilized as well, such as in-class writing assignments and group activities. 

**Exams:** Two in-class exams will be given during the course of the semester, on dates noted on the Tentative Course Outline. These exams are closed book and notes. The exams will
evaluate your understanding of the material, as well as your ability to synthesize and
transfer that knowledge to other scenarios and situations; questions will assess conceptual
understanding as opposed to mere memorization.

You are expected to take exams at the scheduled times. If this is impossible due to
extreme circumstances (illness, death in the family, previously scheduled activities vital
to academic program), please notify me and provide appropriate documentation. No
make-up exams will be given if I am not notified prior to the examination. You will be
required to obtain a note from your physician or advisor explaining the nature of
the conflict.

**Final Project:** A final group project will take the place of a final exam. The project will include a presentation during the last week of class and a final written report.  More details on the project will be distributed later. 

**Instructional Continuity:** If in-person classes are canceled, you will be notified of the instructional continuity plan for this class through Canvas.

**AI and Explainability Policy:** (adapted from Dr. Vanderplas)

- Any use of generative AI must be disclosed in an appendix to your submission - this includes brainstorming, editing, using AI as spell-check/grammar-check, and so on. You must document the following:

  - the version of the generative AI used

  - the full sequence of prompts and responses

  - any additional inputs you provided to the AI system

  - a “diff” between the AI responses and your submission, showing exactly what was generated by the AI system and what you changed.

It may be useful to leverage AI tools to ensure that your work conforms to grammar and style guidelines, but I very highly discourage the use of generative AI for content or code (I've seen it generate incorrect code too many times).

- You must be able to explain any work you turn in, including code. If you cannot explain the logic behind your approach as well as how it works in practice, then you will not receive credit for your submission.

\newpage

**Department Grade Appeal Policy:** The Department of Statistics [grade appeal policy](https://statistics.unl.edu/department-policies-grade-appeals-academic-integrity/)

**Academic Integrity:** You are encouraged to work together on problems and exercises, but the work you turn in must be your own (unless the assignment specifically states otherwise). Work on exams must be your own. University policy will be followed in cases of academic dishonesty: In cases where an instructor finds that a student has committed any act of academic dishonesty, the instructor may in the exercise of his or her professional judgment impose an academic sanction as severe as giving the student a failing grade in the course. Before imposing an academic sanction the instructor shall first attempt to discuss the matter with the student. If deemed necessary by either the instructor or the student, the matter may be brought to the attention of the student's major advisor, the instructor's department chairperson or head, or the dean of the college in which the student is enrolled. For additional details see [the department policy.](https://statistics.unl.edu/department-policies-grade-appeals-academic-integrity/)

**Services for Students with Disabilities:** The University strives to make all learning experiences as accessible as possible. If you anticipate or experience barriers based on your disability (including mental health, chronic or temporary medical conditions), please let your instructor know immediately so that you can discuss options privately. To establish reasonable accommodations, your instructor may request that you register with Services for Students with Disabilities. If you are eligible for services and register with the office, make arrangements with your instructor as soon as possible to discuss your accommodations so they can be implemented in a timely manner. SSD is located in 117 Louise Pound Hall and can be reached at 402-472-3787.

**University Policies:** All [university-wide course policies.](https://executivevc.unl.edu/academic-excellence/teaching-resources/course-policies/)


[***TENTATIVE***]{.underline} **Course Outline**

| Week | Dates | Notes | Topics |
|---------|------------|-------------|-----------------------|
| 1 | 25-27 August |  | Introduction: basic concepts in probability sampling and the survey process |
| 2 | 1-3 September |  | Introduction: bias, questionnaire considerations  |
| 3 | 8-10 September |  | Simple probability samples |
| 4 | 15-17 September |  | Simple probability samples |
| 5 | 22-24 September |  | Simple probability samples; systematic sampling; stratified sampling |
| 6 | 29 Sept - 1 Oct |  | Stratified sampling; allocation|
| 7 | 6-8 October |  | Allocation |
| 8 | 13-15 October |  | Review and **Exam I** |
| 9 | 20-22 October | No class on 20 Oct | Ratio estimation |
| 10 | 27-29 October |  | Ratio estimation |
| 11 | 3-5 November |  | Regression estimation; domain estimation  |
| 12 | 10-12 November |  | Post stratification; cluster sampling |
| 13 | 17-19 November |  | Cluster sampling |
| 14 | 24-26 November | No class on 26 Nov | Cluster sampling |
| 15 | 1-3 December |  | Review and **Exam II** |
| 16 | 8-10 December |  | **Final project presentations** |
| Finals Week |  | No final exam | **Final project papers due Monday, 14 December at 9:00 am** |
